const MAX_DEFAULT_LIMIT = 50;
const MIN_DEFAULT_OFFSET = 0;
const WATCH_DEVICE = 'watch';
const MOBILE_DEVICE = 'mobile';
const STREAM_STATE = {
  ACTIVE: 'ACTIVE',
  UPDATING: 'UPDATING',
  CREATING: 'CREATING',
  DELETING: 'DELETING',
};
const PRODUCTION_ENV = 'production';

module.exports = {
  MAX_DEFAULT_LIMIT,
  MIN_DEFAULT_OFFSET,
  WATCH_DEVICE,
  MOBILE_DEVICE,
  STREAM_STATE,
  PRODUCTION_ENV,
};
