version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: collector-api
    ports:
      - "3000:3000"
    volumes:
      - .:/home/nodejs/src
    env_file: .env